### ISSUE TITLE
Camera frame rate

### ISSUE THREAD

**Issue by soumyaaymous** [soumyaaymous/eyeBlinkBehaviour#5]
In some of the laptops (peculiarly in some of the accounts and not all) there is a lag between the camera image and data stamp.
As Upi suggested, can the camera be made to run at 100Hz and not more?

**Comment by dilawar** [comment]
https://github.com/BhallaLab/MouseBehaviour/blob/e7c60f50c5bc1cc9c457e55da81425270961f471/PointGreyCamera/CMakeLists.txt#L19 

Change the 'EXPECTED_FPS` and rerun.

Locally this file should be in `PointGreyCamera/CMakeLists.txt` (Line no 19).
